// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWLR0KKCA8sFwJ73V7vzzMBtgW3OD4_lw',
    appId: '1:387587913311:web:55e079c5b8e006ef530dea',
    messagingSenderId: '387587913311',
    projectId: 'tyamoapp11',
    authDomain: 'tyamoapp11.firebaseapp.com',
    storageBucket: 'tyamoapp11.appspot.com',
    measurementId: 'G-Z4BTZ6XMQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqLnkYu1tufU6IPbZ1d_U6nQftp8Vmi18',
    appId: '1:387587913311:android:673e875244719f59530dea',
    messagingSenderId: '387587913311',
    projectId: 'tyamoapp11',
    storageBucket: 'tyamoapp11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq9MQUVt0q30Ea-v70_3qKX0bPQjj-RRI',
    appId: '1:387587913311:ios:4e39a64073b25db9530dea',
    messagingSenderId: '387587913311',
    projectId: 'tyamoapp11',
    storageBucket: 'tyamoapp11.appspot.com',
    iosBundleId: 'com.example.tyamo',
  );
}
